### ISSUE TITLE
Bug: Severity.<SEVERITY>.ordinal() returns the wrong ordinal. And Severity.isLessSevereThan() does not work correctly.

### ISSUE THREAD

**Issue by steffenvan** [adamcin/oakpal#100]
I'm writing tests in AEM CM that imports this library. The test code verifies that a `CheckReport` contains certain severity levels. Because of failing tests, I found out that when I call `Severity.MINOR.ordinal()`, it returns `0` instead of the expected `2`, because that call to ordinal returns the ordinal that java assigns to it internally. To me, this has the unnecessary side-effect that it's quite confusing - why have we defined them this way? Especially because there is a private field in `Severity` whose name is also `ordinal`. So if as a client you call `Severity.MINOR.ordinal()` it returns the ordinal assigned by Java itself (which is 0 since it's defined first) instead of the one assigned during construction, `2`. Particularly because as a client, I will call `Severity.isLessThanSevere()` and can see that it uses this ordinal field.

Besides, I think the semantics around `Severity.isLessSevereThan(Severity other)` is wrong. Assume that we call 
```Java
boolean foo = Severity.SEVERE.isLessSevereThan(Severity.SEVERE);
// foo == false
```
which is incorrect. Because inside `CheckReport` we have:
```Java
default Collection<Violation> getViolations(Severity atLeastAsSevere) {
        if (atLeastAsSevere == null) {
            return getViolations();
        }
        return getViolations().stream().filter(v -> v != null
                && !v.getSeverity().isLessSevereThan(atLeastAsSevere))
                .collect(Collectors.toList());
    }
```
So let's assume that we have a `CheckReport report` with 2 `Severity.SEVERE` violations. Then we have:
 
```Java
CheckReport report = getReport(...);
report.getViolations(Severity.SEVERE).size() == 2;
report.getViolations(Severity.MAJOR).size() == 2;
report.getViolations(Severity.MINOR).size() == 2;
```
which I don't think is intended.

**Comment by adamcin** [comment]
@steffenvan Thank you for the report. I didn't notice the lexical clash with the Enum.ordinal() method until you mentioned it. It was never my intention to expose the numeric value for the Severity type, and because I haven't exposed it yet, it could be renamed to avoid confusion when reading the source code without requiring a increase to the exported api package version. However, because this value is not exposed as part of the API, I recommend that you avoid writing tests that depend on this private value. A Severity enum value should be serialized using the name(), not the ordinal().

The behavior of the CheckReport.getViolations() method is working as intended. The severity parameter is intended to be used in order to "ignore violations that do not meet this minimum level of severity". A report with two SEVERE violations has no violations worthy of being ignored, because there is no level of Severity that is more severe than SEVERE. If the CheckReport had two MAJOR violations, those would be ignored if you passed SEVERE as the method parameter.
