### ISSUE TITLE
remove unused dependency on oak-core-spi

### ISSUE THREAD

**Issue by reschke** [adamcin/oakpal#47]
It's not only not needed, but will cause future breakage (see https://issues.apache.org/jira/browse/OAK-7358, resolved in Oak 1.26.0).

**Comment by joerghoh** [comment]
@adamcin do you already have a schedule to release a version with this fix?

**Comment by adamcin** [comment]
@joerghoh @reschke After further analysis, oak-core-spi is actually tightly coupled to the OakMachine class, since it creates and runs an oak repository. Simply removing the explicit dependency doesn't remove the implicit dependency from oakpal-core to oak-core-spi. And unfortunately, the refactoring needed to fully eliminate the direct dependency will require an oakpal version 2 release, so it's a bit bigger than I expected. I don't have a schedule at the moment. I'm open to interim solutions if an osgi import version conflict is still affecting acs-aem-commons. Otherwise, I have to split oakpal-core into its own oakpal-spi and oakpal-core variants and include a lot of other changes that are waiting for a major semantic release.

**Comment by adamcin** [comment]
This is now fixed with the v2.0.0 release.
