### ISSUE TITLE
Provide CLI dist with Windows binary launcher

### ISSUE THREAD

**Issue by pun-ky** [adamcin/oakpal#50]
https://github.com/Cognifide/gradle-aem-plugin/pull/678/files#r403881556

seems that in the archive there is only bin/oakpal.sh ; however to make my tool cross-platform, when I need to launch oakpal, I need to use Windows script for Windows build users (bin/oakpal.bat).

it would be nice if it will be added soon. 
Greetings, Krystian

**Comment by pun-ky** [comment]
as e.g in vault-cli binary script for Unix is having no extension *.sh - it is just `bin/vault`, but the Windows one is `bin/vault.bat`. It would be nice to follow that general convention (not seen only in Vault, but also in other tools).

**Comment by pun-ky** [comment]
it is blocking me from releasing the next version of my AEM plugin. Is there any chance that within the next days will arrive 1.5.2 with a fix? @adamcin - I could prepare PR with required changes.

Greetings, Krystian

**Comment by adamcin** [comment]
I'll get a 1.5.2 release out this week.

Mark Adamcin

**Comment by pun-ky** [comment]
Nice 🙂 I already prepared working/tested Windows script. I will create PR tomorrow morning.

**Comment by pun-ky** [comment]
ETA? :) tomorrow or Monday possible?

**Comment by adamcin** [comment]
@pun-ky I am really terribly sorry about the delay with this. I just got some time to focus on it. v1.5.2 has been published.

**Comment by pun-ky** [comment]
No pressure. Finally you found time for me. I appreciate it.

Have a nice day 🙂

**Comment by pun-ky** [comment]
I confirm that my integration with OakPAL is **working properly** on Unix'es and Windows.

https://github.com/Cognifide/gradle-aem-plugin/blob/develop/src/main/kotlin/com/cognifide/gradle/aem/common/pkg/PackageValidator.kt

When implementing that integration I spotted 2 issues that potentially could be improved or handled in a more appropriate way that you could suggest. Assuming that I am not building Opear JAR but using OakPAL with Opear directory which contents are prepared just before running OakPAL package scanning:

1. Whenever I specify `-p custom-plan.json` it only works with plan names already defined in META-INF/MANIFEST.MF. I would like to be able to load any other plan that I provide in Opear directory (or even provide a plan at an absolute path) without a need to update MANIFEST.MF so that OakPAL will be able to load it. Currently, there is such a limitation. I implemented a workaround for it: https://github.com/Cognifide/gradle-aem-plugin/blob/develop/src/main/kotlin/com/cognifide/gradle/aem/common/pkg/PackageValidator.kt#L167
2. I am not sure if preparing the initial state of repository is OK by scanning one extra package before other packages. I am preparing a minimal initial package:

https://github.com/Cognifide/gradle-aem-plugin/blob/develop/src/main/kotlin/com/cognifide/gradle/aem/common/pkg/PackageValidator.kt#L173-L194
https://github.com/Cognifide/gradle-aem-plugin/blob/develop/src/main/kotlin/com/cognifide/gradle/aem/common/pkg/PackageValidator.kt#L199

- without any JCR content 
- with one dummy Vault workspace filter (to avoid violation reported)
- with META-INF/vault/privileges.xml to pre-populate crx:replicate privilege
- with META-INF/vault/nodetypes.cnd to pre-populate AEM specific nodetypes

Any hints appreciated.

**Comment by pun-ky** [comment]
@adamcin?

**Comment by adamcin** [comment]
@pun-ky 
I'll answer question (2) first. It's okay to "scan" one extra package, but the oakpal plan.json format can reference `preInstallUrls`, as an array of URLs to packages, which can be absolute or relative to the `$OAKPAL_OPEAR` file URL base.

See:
https://github.com/adamcin/oakpal/blob/c6503fd52ec82dec44790839955739202efb0029/core/src/main/java/net/adamcin/oakpal/core/OakpalPlan.java#L338

To answer question (1), an undocumented behavior at the moment is that when `$OAKPAL_OPEAR` references a directory rather than a Jar file, and the directory does not contain a META-INF/MANIFEST.MF file, and `$OAKPAL_OPEAR/plan.json` is a file, it treats "plan.json" as the default plan name. The missing piece here with this undocumented behavior is there is no CLI or API option to specify a plan classloader, so it's not currently possible to reference checks or checklists embedded in jars. You should be able to override the basic checklist details, however. 

https://github.com/adamcin/oakpal/blob/c6503fd52ec82dec44790839955739202efb0029/core/src/main/java/net/adamcin/oakpal/core/OpearFile.java#L195

**Comment by pun-ky** [comment]
Ideally if I could specify both any plan url and pre install url from CLI 🙂

Thanks for explanation.

**Comment by adamcin** [comment]
@pun-ky I'll see what I can do.
