### ISSUE TITLE
Make net.adamcin.oakpal.core.checks.Rule constructor public?

### ISSUE THREAD

**Issue by justinedelson** [adamcin/oakpal#6]
I'm trying to programmatically create a Rule object and it seems weird to have to construct a JSONObject for this purpose. Is there a reason the constructor is private?

**Comment by justinedelson** [comment]
And similarly (but I can create a separate issue for this), I'm wondering if `Paths.Check` could be a static inner class.

**Comment by adamcin** [comment]
I am self-conscious about the RuleType enum elements. I wish I had started out with the reverse for the java API, `INCLUDE("ALLOW")` and `EXCLUDE("DENY")`, so I have been keeping the Rule constructor private until I fixed that :) I guess I shall fix it now.

As to `Paths.Check`, I had a (probably YAGNI) thought that someone might want to subclass the `Paths` class, and I wanted the default getCheckName() method to return the subclass name by default, https://github.com/adamcin/oakpal/blob/master/core/src/main/java/net/adamcin/oakpal/core/checks/Paths.java#L75-L78 . That really wasn't clearly thought out all the way, since I probably should have made the `Check` a protected class if all I wanted was subclassing convenience. 

Anyway, the important interface for check construction is `(new ProgressCheckFactory()).newInstance(JSONObject)` so as long as that holds the rest is aesthetics.

**Comment by adamcin** [comment]
@justinedelson I did some more thinking about the API for building checks, and I decided that the standard checks shouldn't try to be extensible and that the Check constructors should be made package private to be accessible only to unit tests. 

Because this means that the `ProgressCheckFactory.getInstance()` method will become the primary means of constructing these checks programmatically, I added a [simple DSL](https://github.com/adamcin/oakpal/blob/master/core/src/main/java/net/adamcin/oakpal/core/OrgJson.java)  for fluent construction of `org.json.*` types that should at least make it less painful to use that API from Java.

see https://github.com/adamcin/oakpal/blob/master/core/src/test/java/net/adamcin/oakpal/core/checks/PathsTest.java#L51 and https://github.com/adamcin/oakpal/blob/master/core/src/test/java/net/adamcin/oakpal/core/checks/JcrPropertiesTest.java#L48 for some examples of how I'm using it.

**Comment by justinedelson** [comment]
That’s great. Thanks!
